name: Docker Build & Push
on:
  push: {branches: [main]}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.extract_branch.outputs.branch }}

      # Grab the 'usurp' binary
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "samjarrett/usurp"
          version: "tags/0.0.1"
          file: "usurp_linux_amd64"
          target: ./usurp
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: chmod +x usurp
          
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}