name: Docker Build & Push
on:
  push:

jobs:

  metadata:
    name: Gather Metadata
    runs-on: ubuntu-20.04
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
      docker_image: ghcr.io/${{ github.repository }}:${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

  test_run:
    needs: [metadata]
    name: Test Run
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ needs.metadata.outputs.docker_image }}
    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: docker-compose build

      - name: Start containers
        run: |
          docker-compose up --detach
          timeout 60 docker-compose logs

      - name: Ensure containers are still running
        run: |
          docker-compose exec minecraft echo hi there

  docker:
    name: Docker Build
    needs: [test_run]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ needs.metadata.outputs.docker_image }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
